#!/usr/bin/env python
# -*- coding: utf-8 -*-
# PYTHON_ARGCOMPLETE_OK

import argparse
import argcomplete
from termux_call.lib import make_call, get_contact_list

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("contact_name", choices=get_contact_list().keys())
    argcomplete.autocomplete(parser)
    args = parser.parse_args()
    make_call(args.contact_name)


if __name__ == "__main__":
    main()
